name: build and deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        run: shellcheck telegraf/run.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker files
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target telegraf \
            --docker-hub ghcr.io/${{ github.repository_owner }}

  push-config-to-addon-repo:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          path: main
      - name: addon
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          path: addon
          repository: jnull/hassio-addons

      - name: setup local env
        run: |
          \cp -Rv main/telegraf/config.yml addon/telegraf/config.yml
          \cp -Rv main/README.md addon/telegraf/README.md
          cd addon
          git config --local user.email "admin@jnull.org"
          git config --local user.name "jnull"
          git add .
          git commit -m "Add changes"
        continue-on-error: true

      - name: copy config to repo dir in case of change
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REGISTRY_CREDS }}
          repository: jnull/hassio-addons
          directory: addon
